
name: Matrix Workflow
#для релиза
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build classlibrary
      run: dotnet build src/Matrix.Domain/Matrix.Domain.csproj
    - name: Build application
      run: dotnet build src/Matrix.App/Matrix.App.csproj
  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests for release build
      run: dotnet test tests/tests.csproj --configuration Release

  analyze:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run code analysis
      run: dotnet tool install -g dotnet-format && dotnet format src/Matrix.App/Matrix.App.csproj
#для отладки
  # build-debug:
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Build classlibrary in Debug
  #     run: dotnet build src/Matrix.Domain/Matrix.Domain.csproj --configuration Debug
  
  # test-debug:
  #   needs: build-debug
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Run tests for debug build
  #     run: dotnet test tests/tests.csproj --configuration Debug
